# List of all codes used in the lønseddel

# Spec = Kort navn af koden
# hasAntal = om den har en værdi under kolonnen antal
# hasVærdi = om den har en værdi under kolonnen værdi
# hasSats = om den har en værdi under kolonnen sats
# hasBeløb = om den har en værdi under kolonnen beløb

# spec_amount = Navnet + evt. ekstra "semi-kolonner" der er under kolonnen Specifikation
# Eg. 842 : Orlov u/løn og feriedage har ud over navnet 2 ekstra kolonner hvilket giver 3

kode = {
    '1173': {'spec': 'Fri Telefon', 'hasAntal': True, 'hasSats': False, 'hasBeløb': False, 'spec_amount': 1},
    '2001': {'spec': 'Timer', 'hasAntal': True, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 1},
    '5092': {'spec': 'Employee match contribution', 'hasAntal': True, 'hasSats': False, 'hasBeløb': False,
             'spec_amount': 1},
    '8716': {'spec': 'Ulykkesforsikring', 'hasAntal': True, 'hasSats': False, 'hasBeløb': False, 'spec_amount': 1},
    '8750': {'spec': 'ATP bidrag', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '8861': {'spec': 'Arbejdsmarkedbidrag', 'hasAntal': False, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 2},
    '8906': {'spec': 'A-indk', 'hasAntal': False, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 3},
    '9220': {'spec': 'Contribution', 'hasAntal': True, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 1},
    '9414': {'spec': 'Aktivitetsforening', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9463': {'spec': 'Kantine', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9993': {'spec': 'Overført til konto', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9761': {'spec': 'Afregnet feriepenge ferieår 2. del', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True,
             'spec_amount': 1},
    '9762': {'spec': 'Arbejdsmarkedsbidrag ferie ferieår 2. del', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True,
             'spec_amount': 1},
    '9766': {'spec': 'A-indk ferie ferieår 2. del', 'hasAntal': False, 'hasSats': True, 'hasBeløb': True,
             'spec_amount': 3},
    '9767': {'spec': 'Feriepenge netto feriekonto ferieår 2. del', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True,
             'spec_amount': 1},
    '3018': {'spec': 'PPP', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9781': {'spec': 'Afregnet feriepenge ferieår 1. del', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True,
             'spec_amount': 1},
    '9782': {'spec': 'Arbejdsmarkedsbidrag ferie ferieår 1. del', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True,
             'spec_amount': 1},
    '9786': {'spec': 'A-indk ferie ferieår 1. del', 'hasAntal': False, 'hasSats': True, 'hasBeløb': True,
             'spec_amount': 3},
    '9787': {'spec': 'Feriepenge netto feriekonto ferieår 1. del', 'hasAntal': True, 'hasSats': True, 'hasBeløb': True,
             'spec_amount': 1},
    '9990': {'spec': 'Manglende træk', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '1001': {'spec': 'Månedsløn', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '1023': {'spec': 'Løntræk Smartphones', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '5090': {'spec': 'Værdi af arbejdsgiverbetalt sundhedsforsikring', 'hasAntal': True, 'hasSats': False,
             'hasBeløb': False, 'spec_amount': 1},
    '8720': {'spec': 'Firmapensionsbidrag egen andel', 'hasAntal': False, 'hasSats': True, 'hasBeløb': True,
             'spec_amount': 1},
    '9206': {'spec': 'Kilometergodtgørelse', 'hasAntal': True, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 1},
    '9405': {'spec': 'Udbetalt via rejseafregning', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True,
             'spec_amount': 1},
    '8721': {'spec': 'Firmapension firmaandel', 'hasAntal': False, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 1},
    '9221': {'spec': 'Additional contribution', 'hasAntal': True, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 1},
    '842': {'spec': 'Orlov u/løn og feriedage', 'hasAntal': True, 'hasSats': False, 'hasBeløb': False,
            'spec_amount': 3},
    '9016': {'spec': 'Virksomhed køb', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '520': {'spec': 'Ferie', 'hasAntal': True, 'hasSats': False, 'hasBeløb': False, 'spec_amount': 3},
    '8748': {'spec': 'Månedsvis timelønnede - ferietimer til ATP', 'hasAntal': True, 'hasSats': False, 'hasBeløb': False,
             'spec_amount': 1},
    '4020': {'spec': 'Refferal bonus', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '750': {'spec': 'Afholdt ferie', 'hasAntal': True, 'hasSats': False, 'hasBeløb': False, 'spec_amount': 3},
    '3010': {'spec': 'Refferal bonus', 'hasAntal': False, 'hasSats': False, 'hasBeløb': False, 'spec_amount': 1},
    '8632': {'spec': 'Feriefri - Ny Saldo - udbetaling/træk', 'hasAntal': True, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 1},
    '8676': {'spec': 'Fritvalg, Udbetaling.', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9631': {'spec': 'Feriepenge optjent sidste år', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9637': {'spec': 'Feriepenge i alt sidste år', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9638': {'spec': 'Arbejdsmarkedsbidrag Feriepenge i alt sidste år', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9646': {'spec': 'A-indk Feriepenge i alt sidste år', 'hasAntal': False, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 3},
    '9655': {'spec': 'Feriepenge netto sidste år til feriekonto', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9800': {'spec': 'Afregnet feriepenge - overgangsperiode', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9801': {'spec': 'Afregnet feriepenge - overgangsperiode Arbejdsmarkedsbidrag', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '9805': {'spec': 'Afregnet feriepenge - overgangsperiode A-indk', 'hasAntal': False, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 3},
    '9808': {'spec': 'Afregnet feriepenge - overgangsperiode Feriekonto', 'hasAntal': True, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '4001': {'spec': 'Timer', 'hasAntal': True, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 1},
    '3015': {'spec': 'udbetalt 2,4% Fritvalgskonto', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '8311': {'spec': 'Ferietillæg', 'hasAntal': False, 'hasSats': False, 'hasBeløb': True, 'spec_amount': 1},
    '8606': {'spec': 'Afregning feriefri gl. saldo', 'hasAntal': True, 'hasSats': True, 'hasBeløb': True, 'spec_amount': 1},

}
